# Generated by Django 2.0.4 on 2019-07-07 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Publicar_trabajo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aptitude_validadas',
            name='Usuario',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
