# Generated by Django 2.0.4 on 2019-06-29 23:13

import Publicar_trabajo.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Publicar_trabajo', '0002_auto_20190624_0700'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aptitudes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Area', models.CharField(blank=True, max_length=50, null=True)),
                ('Descripccion', models.TextField()),
                ('Fecha', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Cuestionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comuna', models.CharField(blank=True, max_length=50, null=True)),
                ('Pais', models.CharField(blank=True, max_length=50, null=True)),
                ('Ciudad', models.CharField(blank=True, max_length=50, null=True)),
                ('Estado', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(blank=True, max_length=120, null=True)),
                ('Rut', models.CharField(blank=True, max_length=20, null=True)),
                ('Imagen', models.ImageField(blank=True, null=True, upload_to=Publicar_trabajo.models.content_file_name)),
                ('Telefono_C', models.CharField(blank=True, max_length=50, null=True)),
                ('Correo', models.CharField(blank=True, max_length=100, null=True)),
                ('Direccion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Publicar_trabajo.Direccion')),
                ('Usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripcion', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Respuestas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Informacion', models.TextField()),
                ('Validez', models.BooleanField()),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='trabajo',
            name='Area',
        ),
        migrations.DeleteModel(
            name='Trabajo',
        ),
        migrations.AddField(
            model_name='pregunta',
            name='Respuestas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Publicar_trabajo.Respuestas'),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='Usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='Preguntas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Publicar_trabajo.Pregunta'),
        ),
    ]
