# Generated by Django 2.0.4 on 2019-07-07 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Publicar_trabajo', '0002_auto_20190707_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aptitude_validadas',
            name='Usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Publicar_trabajo.Persona'),
        ),
    ]
