# Generated by Django 2.0.4 on 2019-06-29 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Publicar_trabajo', '0004_areas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aptitudes',
            name='Area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Publicar_trabajo.Areas'),
            preserve_default=False,
        ),
    ]
