# Generated by Django 2.0.4 on 2019-06-29 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publicar_trabajo', '0005_auto_20190629_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='aptitudes',
            name='Nombre',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
