# Generated by Django 2.0.4 on 2019-06-30 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Publicar_trabajo', '0006_aptitudes_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pregunta',
            old_name='Descripcion',
            new_name='a',
        ),
        migrations.AddField(
            model_name='pregunta',
            name='Respuesta_correcta',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='b',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='c',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='d',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='pregunta',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='Respuestas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Publicar_trabajo.Respuestas'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='Usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
