# Generated by Django 2.0.4 on 2019-06-30 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Publicar_trabajo', '0007_auto_20190630_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuestionario',
            name='Preguntas',
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='Aptitud_vinculada',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Publicar_trabajo.Aptitudes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pregunta',
            name='Cuestionario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Publicar_trabajo.Cuestionario'),
            preserve_default=False,
        ),
    ]
