# Generated by Django 2.0.4 on 2019-07-01 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Publicar_trabajo', '0008_auto_20190630_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='Aptitud_vinculada',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Publicar_trabajo.Aptitudes'),
            preserve_default=False,
        ),
    ]
