# Generated by Django 2.0.4 on 2019-07-03 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publicar_trabajo', '0009_pregunta_aptitud_vinculada'),
    ]

    operations = [
        migrations.RenameField(
            model_name='direccion',
            old_name='Estado',
            new_name='Calle',
        ),
        migrations.AddField(
            model_name='direccion',
            name='Numero_de_calle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
