# Generated by Django 2.0.4 on 2019-07-06 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Publicar_trabajo', '0010_auto_20190703_0416'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aptitude_validadas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Aptitud_validada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Publicar_trabajo.Aptitudes')),
                ('Usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
