# Generated by Django 2.0.4 on 2019-07-06 07:11

import Publicar_trabajo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publicar_trabajo', '0011_aptitude_validadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='aptitudes',
            name='Imagen',
            field=models.ImageField(blank=True, null=True, upload_to=Publicar_trabajo.models.content_file_name),
        ),
    ]
