# Generated by Django 2.0.4 on 2019-07-06 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publicar_trabajo', '0012_aptitudes_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='aptitudes',
            name='Usuario',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
