# Generated by Django 2.0.4 on 2019-07-06 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Publicar_trabajo', '0014_auto_20190706_0722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aptitudes',
            name='Usuario',
        ),
    ]
