# Generated by Django 2.0.4 on 2019-06-29 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registro_fullpega', '0007_direccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='Areas_interes',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Direccion',
        ),
        migrations.DeleteModel(
            name='Areas',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
