# Generated by Django 2.0.4 on 2019-07-08 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declarar_SVA', '0002_portafolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='portafolio',
            name='Nombre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
